ubse.plugin.name=mempooling
ubse.plugin.pkg=libmempooling.so

# 容器超分场景，是否启用PageCache迁移功能
ucache.enable=false
rmrs.ipc.timeout=180
# 内存碎片场景，是否必须同平面(true:必须同平面，false:优先同平面)
rmrs.fragment.mustSamePlane=true
# 内存碎片场景，借用是否切分为4G粒度（true:切分，false:不切分）
rmrs.fragment.enableBorrowSplit=true
# 超分场景，是否为虚机多numa场景（true:虚机多numa场景，false:单numa场景）
overcommit.enableMultiNuma=false