# memExport plugin. Default value: 201
#memExport=201
# memMaster plugin. Default value: 901
#memMaster=901
# memAgent plugin. Default value: 902
#memAgent=902
# ssu plugin. Default value: 202
# ssu=202
# ssuMaster plugin. Default value: 204
# ssuMaster=204
# ssuAgent plugin. Default value: 204
# ssuAgent=204
# vm plugin. Default value: 205
virt_agent=205
# rackMetric plugin. Default value: 206
#rackMetric=206
# dpu plugin. Default value: 207
# dpu=207
# mem-predict plugin. Default value: 910
# mem-predict=910
mempooling=777
# ucache=778
#memCliMaster=211
#memCliAgent=212
mempoolingcli=877
