apiVersion: v1
kind: Pod
metadata:
  name: test-pod-01
  namespace: kube-system
  labels:
    remote-mem-allocation-ratio: "25"
spec:
  nodeName: worker1
  containers:
  - name: test-pod-01
    image: docker.io/library/numa-stress:v1.0
    command: ["/bin/sh", "-c", "sleep 864000"]
    resources:
      requests:
        cpu: "4"
        memory: "14Gi"
      limits:
        cpu: "4"
        memory: "16Gi"
    securityContext:
      privileged: true
      allowPrivilegeEscalation: true
      capabilities:
        add:
          - SYS_ADMIN