apiVersion: v1
kind: Pod
metadata:
  name: pod-for-shm
  namespace: kube-system
spec:
  nodeName: master
  terminationGracePeriodSeconds: 5
  securityContext:
    supplementalGroups:
      - 1024
      - 4177
  hostPID: false  # 共享主机PID命名空间
  volumes:
    - name: ubs-mem
      hostPath:
        path: /usr/local/ubs_mem/
        type: Directory
    - name: mxm-agent-ipc-server
      hostPath:
        path: /run/memory/
        type: Directory
    - name: boundscheck-volume
      hostPath:
        path: /usr/lib64/libboundscheck.so
        type: File
    - name: libobmm-1-0-1
      hostPath:
        path: /usr/lib64/libobmm.so.1.0.1
        type: File
    - name: libobmm-1
      hostPath:
        path: /usr/lib64/libobmm.so.1
        type: File
    - name: libnuma-1-0-0
      hostPath:
        path: /usr/lib64/libnuma.so.1.0.0
        type: File
    - name: libnuma-1
      hostPath:
        path: /usr/lib64/libnuma.so.1
        type: File
    - name: libhcom-so-0-0-1
      hostPath:
        path: /usr/lib64/libhcom.so.0.0.1
        type: File
    - name: libhcom-so-0
      hostPath:
        path: /usr/lib64/libhcom-so-0
        type: File
    - name: ko
      hostPath:
        path: /tmp/memborrow/shm_demo
        type: File
    - name: shared-memory
      csi:
        driver: shm-csi-driver
        volumeAttributes:
          type: shareMem
          identity: testshm
  containers:
    - name: numaaaaa
      image: docker.io/library/numa-stress:v1.0
      command: ["/bin/bash", "-c", "sleep infinity"]  # 使用bash
      env:
        - name: LD_LIBRARY_PATH
          value: "/usr/lib64/:/host/usr/local/ubs_mem/lib/:"
      volumeMounts:
        - name: boundscheck-volume
          mountPath: /usr/lib64/libboundscheck.so
        - name: libobmm-1-0-1
          mountPath: /usr/lib64/libobmm.so.1.0.1
        - name: libobmm-1
          mountPath: /usr/lib64/libobmm.so.1
        - name: libnuma-1-0-0
          mountPath: /usr/lib64/libnuma.so.1.0.0
        - name: libnuma-1
          mountPath: /usr/lib64/libnuma.so.1
        - name: libhcom-so-0-0-1
          mountPath: /usr/lib64/libhcom.so.0.0.1
        - name: libhcom-so-0-0-1
          mountPath: /usr/lib64/libhcom.so.0
        - name: ubs-mem
          mountPath: /host/usr/local/ubs_mem/
        - name: mxm-agent-ipc-server
          mountPath: /run/matrix/memory/
        - name: ko
          mountPath: /ko/shm_demo
        - name: shared-memory
          mountPath: /dev
          mountPropagation: "HostToContainer"
      securityContext:
        runAsUser: 4178
        runAsGroup: 4178
        privileged: false
        capabilities:
          drop:
            - ALL
